create table if not exists public.workzo_analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null default 'unknown_session',
  event text not null default 'unknown_event',
  path text not null default '/',
  source text not null default 'Direct / unknown',
  device text not null default 'unknown',
  recruiter text not null default 'Unknown recruiter',
  role text not null default 'Unknown role',
  mode text not null default 'standard',
  trust numeric null,
  pressure numeric null,
  score numeric null,
  timestamp timestamptz null,
  received_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists workzo_analytics_events_session_idx
  on public.workzo_analytics_events (session_id, received_at desc);

create index if not exists workzo_analytics_events_event_idx
  on public.workzo_analytics_events (event, received_at desc);

create index if not exists workzo_analytics_events_device_idx
  on public.workzo_analytics_events (device, received_at desc);
