"use client";

import { ArrowLeft, MoreVertical, Settings, Volume2 } from "lucide-react";
import Link from "next/link";
import RecruiterVideoPanel from "./RecruiterVideoPanel";
import InterviewScorePanel from "./InterviewScorePanel";
import LiveCopilotPanel from "./LiveCopilotPanel";
import LiveTranscriptPanel from "./LiveTranscriptPanel";
import type { InterviewLayoutProps } from "./types";

export default function InterviewDesktopLayout({ setup, signal, transcript, ui, actions }: InterviewLayoutProps) {
  return (
    <main className="min-h-screen bg-[#050a12] text-white">
      <header className="sticky top-0 z-40 border-b border-white/10 bg-[#07101c]/95 px-5 py-4 backdrop-blur"><div className="flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><button type="button" onClick={actions.onBack} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/5 hover:bg-white/10" aria-label="Back to dashboard"><ArrowLeft className="h-5 w-5" /></button><Link href="/dashboard" className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-500 text-xl font-black">W</div><span className="text-2xl font-black">WorkZo <span className="text-blue-400">AI</span></span></Link><div className="h-8 w-px bg-white/10" /><h1 className="truncate text-2xl font-black">{setup.targetRole}</h1><span className="h-3 w-3 rounded-full bg-emerald-400" /><span className="rounded-full border border-blue-300/20 bg-blue-400/10 px-4 py-1 text-sm font-black text-blue-200">{signal.mood === "Engaged" ? "INTERESTED" : signal.mood.toUpperCase()}</span></div><div className="flex items-center gap-3"><span className="text-sm text-slate-200">{ui.elapsedLabel}</span><button type="button" onClick={actions.onEnd} className="rounded-2xl border border-red-400/30 px-5 py-3 font-black text-red-200 hover:bg-red-500/10">End Interview</button><button type="button" onClick={actions.onToggleMute} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/5"><Volume2 className="h-5 w-5" /></button><button type="button" onClick={actions.onToggleSettings} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/5"><Settings className="h-5 w-5" /></button><button type="button" onClick={actions.onToggleMore} className="grid h-12 w-12 place-items-center rounded-2xl border border-white/10 bg-white/5"><MoreVertical className="h-5 w-5" /></button></div></div></header>
      <div className="grid gap-4 p-5 xl:grid-cols-[1fr_460px]"><div className="space-y-4"><RecruiterVideoPanel setup={setup} statusLabel={ui.status === "listening" ? "Listening" : ui.status === "recruiter-speaking" ? "Speaking" : "Interested"} statusTone={ui.status === "listening" ? "LISTENING" : "LIVE"} onToggleMute={actions.onToggleMute} onOpenSettings={actions.onToggleSettings} onEnd={actions.onEnd} /><LiveTranscriptPanel transcript={transcript} collapsed={false} onToggle={actions.onToggleTranscript} onClear={actions.onClearTranscript} showToggle={false} /></div><aside className="space-y-4"><InterviewScorePanel signal={signal} scoreReady={ui.scoreReady} /><LiveCopilotPanel signal={signal} enabled={ui.copilotEnabled} onToggle={actions.onToggleCopilot} /><section className="rounded-3xl border border-white/10 bg-[#0b1424] p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Interview Progress</h2><span className="text-sm text-slate-300">Question {ui.questionIndex} of 12</span></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-violet-500" style={{ width: `${ui.progress}%` }} /></div><p className="mt-2 text-sm text-slate-300">{ui.progress}% Completed</p></section></aside></div>
    </main>
  );
}
